linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120

linters:
  enable-all: true
  disable:
    - scopelint
    - gochecknoglobals
    - dupl
    - unparam
    - maligned

run:
  skip-dirs:
    - vendor 

