notifications:
  email: false

language: go

go:
  - 1.x

env:
  - GO111MODULE=on

install: true

before_script:
  - make install

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - make lint
  - make validate
  - make ineffassign
  - go test -covermode=count -coverprofile=profile.cov .

after_script:
  - goveralls -coverprofile=profile.cov -service=travis-ci
