notifications:
  email: false

language: go

go:
  - 1.x

env:
  - GO111MODULE=on

install: true

before_script:
  - make install

script:
  - make lint
  - make validate
  - make ineffassign
  - go test -v -race -p 1 -covermode=atomic ./...
  - go test -covermode=count -p 1 -coverprofile=profile.cov ./...

after_script:
  - goveralls -coverprofile=profile.cov -service=travis-ci
