notifications:
  email: false

language: go

go:
  - 1.x

env:
  - GO111MODULE=on

install: true

before_script:
  - go get golang.org/x/lint/golint
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get github.com/gordonklaus/ineffassign
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - make lint
  - make validate
  - make ineffassign
  - go test -covermode=count -coverprofile=profile.cov .

after_script:
  - goveralls -coverprofile=profile.cov -service=travis-ci